Repository devstrons/heloworld, pull requests merged in 2021-09, with the labels that each got.

#52 ✨ modified: Java lang
  lang/java.md
Labels: documentation

#43 adding C language
  lang/C.md
Labels: documentation, incomplete

#55 adding python language
  lang/python.md
Labels: documentation

#56 adding dart language
  lang/dart.md
Labels: documentation, area/discuss

#62 ⚗ architectural changes to the project
  .prettierignore
  README.md
  api/index.ts
  api/lang.ts
  lang/c.md
  lang/dart.md
  lang/hexa.md
  lang/javascript.md
  package-lock.json
  package.json
  server/index.js
  server/logger.js
  server/routes/list.js
  server/routes/serve.js
  src/assets/scripts/core/api.js
  src/assets/scripts/core/index.js
  src/assets/scripts/core/parse.js
  vercel.json
Labels: enhancement

#49 feat: Add Gitpod and improve `README.md`
  .gitpod.yml
  README.md
Labels: area/discuss

#59 Update pull request template
  .github/pull_request_template.md
Labels: enhancement
