Repository devstrons/heloworld, pull requests merged in 2022-10, with the labels that each got.

#99 changes for better view of page
  src/assets/styles/_nprogress.css
  src/sections/header/index.html
  src/sections/main/index.css
Labels: hacktoberfest

#100 Adding Scala language
  lang/scala.md
Labels: enhancement

#103 chore: update copyright notices to 2022
  LICENSE
  README.md
Labels: documentation
